
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from "@mui/material";
import theme from "./theme";
import Link from "next/link";
import TemporaryDrawer from "./components/Drawer";
import StackedLineChartIcon from '@mui/icons-material/StackedLineChart';
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LeaderBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>

        <AppRouterCacheProvider>

          <ThemeProvider theme={theme}>
            <Navbar />

            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>

      </body>
    </html>
  );
}
